version: '3'
services:
  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      - POSTGRES_USER=my_app
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=my_app
    ports:
      - '5442:5432'

  php:
    image: webdevops/php-apache:7.4
    container_name: cakephp
    working_dir: /application/webroot
    volumes:
      - ./:/application
    environment:
      - WEB_DOCUMENT_ROOT=/application/webroot
      - DATABASE_URL=postgres://my_app:secret@postgres:5432/my_app
    ports:
      - "8099:80"
